== Lim Yan Ting Project Portfolio

=== Overview - Kitchen Helper

Kitchen Helper is a command line interface (CLI) application that is
mainly targeted for household users who have difficulty in remembering
what they have in their kitchen. This application aids them in the
tracking of ingredients that are currently in their kitchen more
efficiently in terms of buying new ingredients or deducting quantity of
ingredients after they cook a recipe.

=== Contributions

==== Enhancements implemented

* Deletion of ingredients and recipes
** What it does: It allows the user to delete any ingredient or recipe
with regards to the list of ingredients or recipes in Kitchen Helper
respectively.
** Justification: This feature improves the product slightly because a
user may make a mistake and input the wrong parameters for an ingredient
or a recipe. With this feature, the user will be able to delete this
ingredient or recipe that he/she has keyed in and add a new one.
** Highlights: This enhancement was done by deleting the ingredient
based on their index so that the users can delete a specific ingredient
that they want. However, for deletion of recipe, there is an additional
enhancement of deletion by name as the recipe names are unique so the
users can delete a specific recipe by deleting through the names.
* Deduction of quantity of ingredients
** What it does: It allows the user to reduce the quantity of an
ingredient with regards to the list of ingredients in Kitchen Helper.
** Justification: This feature improves the product slightly because a
user may just want to utilize a few quantities of the ingredient without
cooking the recipe. Example, if a user wants to just eat an apple, the
user can use this feature to deduct the quantity of apple by 1.
** Highlights: This enhancement deletes the ingredient automatically if
the final quantity after the deduction is zero for the ingredient.
* Added the deduction of ingredients from list of ingredients after a
user has cooked a recipe
** What it does: It automatically deducts the ingredients found in the
recipe that the user has specified to cook if there are enough and
non-expiring ingredients in the list of ingredients.
** Justification: This feature improves the product slightly because a
user does not have to manually deduct the quantity of ingredients which
increases convenience for the users in managing their ingredients’
inventory.
** Highlights: This enhancement also deletes the ingredient
automatically if the final quantity after the deduction is zero for the
ingredient.

==== Code Contributions

The link below showed my code contributions to Kitchen Helper:

[Functional and Testing
Code](https://nus-cs2113-ay1920s2.github.io/tp-dashboard/#breakdown=true&search=yantingsanity&sort=groupTitle&sortWithin=title&since=2020-03-01&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&tabOpen=true&tabType=authorship&tabAuthor=yantingsanity&tabRepo=AY1920S2-CS2113T-M16-2
